2020-07-30 15:24:34.279 | ERROR    | __main__:test_proxy:40 - Cannot connect to host 192.168.1.3:7777 ssl:None [Connect call failed ('192.168.1.3', 7777)]
2020-07-30 15:24:36.296 | ERROR    | __main__:test_proxy:40 - Cannot connect to host 192.168.1.1:8888 ssl:None [Connect call failed ('192.168.1.1', 8888)]
2020-07-30 15:24:53.279 | ERROR    | __main__:test_proxy:40 - Cannot connect to host 192.168.1.2:6666 ssl:None [Connect call failed ('192.168.1.2', 6666)]
